---
version: 0.1.3
slug: hassio_boringproxy
name: BoringProxy-client for Home Assistant
url: https://github.com/jeynek/hassio_boringproxy
description: Simple client that connects to a BoringProxy-server. A way to give HomeAssistant a public IP without too much hassle.
codenotary: notary@home-assistant.io
advanced: true
arch:
  - armhf
host_network: true
options:
  server: myserver.io
  user: admin
  token: 12345678abcdefgh
  clientid: myhassio
schema:
  server: str
  user: str
  token: str
  clientid: str
startup: application
init: false
